### ISSUE TITLE
Anonymous function expression fails to compile

### ISSUE THREAD

**Issue by alecmerdler** [serulian/compiler#264]
### Description

The Serulian Guide indicates syntax for [anonymous function expressions](https://serulian.io/guide#functions-and-closures), but the compiler throws an error.

### Reproduce

1. Visit https://serulian.io
2. Write the following in the embedded editor: 
```
myFunc := () => 1
```
3. Click "Run" 

**Expected**:
Compiles without error

**Actual:**

```
ERROR: /b/playground.seru:15:1:
  Unexpected token at root level: tokenTypeIdentifer

  myFunc := () => 1
  ^^^^^^^^^^^^^^^^^
```

**Comment by alecmerdler** [comment]
This seems to extend to all top-level resolve statements (`a := 1`).

**Comment by josephschorr** [comment]
Resolve statements are not allowed at the top-level; if you want to assign an anonymous function at the top-level, it must be created as a variable:

```seru
var<function<int>()> myFunc = () => 1
```

Although the preferred syntax (unless you want the function to be reassignable) is:

```seru
function<int> myFunc() {
  return 1
}
```

Only variables, functions and types are allowed at the top-level, to ensure random state is not executed on module load.

**Comment by alecmerdler** [comment]
So you cannot export an immutable value from a module?

**Comment by josephschorr** [comment]
Currently, no, but this is a very good idea. Will add.

**Comment by josephschorr** [comment]
Solved by allowing constant variables to be declared at the top level in v0.2.0:

```seru
const myFunc function<void>() = function () { ... }
```
